# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
gems:
  - jekyll-assets
  - jekyll-assets/compass
  - font-awesome-sass

# Permalinks
permalink: /:year/:month/:day/:title/
paginate: 10

# Setup
title:            Your Awesome Title
description:      A blog using a modified Midnight theme
url:              http://example.org
baseurl:          '' # the subpath of your site, e.g. /blog/


# Author details
email:            your-email@domain.com
name:             Creator Name # For the copyright notice


# Social
github: rcrmn
twitter: rcrmn_
stackoverflow: 672151


# Navigation
navigation:
- text: Home
  url: /
- text: Archive
  url : /archives
- text: About
  url: /about
- text: Portfolio
  url: http://rcrmn.nl/portfolio


# Disqus
disqushandler: ''
